# This files gather compiler flags that are common to g++, clang and
# pathCC

madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wall" "W" "Wextra" "pedantic" "Wshadow")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wpointer-arith" "Wcast-qual" "Wcast-align")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wwrite-strings" "Wctor-dtor-privacy" "Wnon-virtual-dtor")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Woverloaded-virtual" "Wreturn-type" "Wfloat-equal")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-endif-labels" "Wsign-compare" "Wmissing-format-attribute")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-multichar" "Wno-deprecated-declarations" "Wpacked")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wredundant-decls")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wunknown-pragmas" "Wundef" "Wreorder")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wno-conversion")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wdouble-promotion")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Winit-self")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wlogical-op")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wmissing-declarations")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wmissing-include-dirs")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wnoexcept")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wold-style-cast")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsign-conversion")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsign-promo")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wstrict-null-sentinel")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wtrampolines")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wvector-operation-performance")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wzero-as-null-pointer-constant")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wignored-qualifiers")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsequence-point")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wswitch")
# madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-attribute=pure")
# madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-attribute=const")
# madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-attribute=noreturn")
# madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-attribute=format")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-final-types")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-final-methods")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsuggest-override")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wswitch-bool")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wlogical-not-parentheses")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wsizeof-array-argument")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wbool-compare")
# madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Winline")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wshift-negative-value")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wshift-overflow")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wtautological-compare")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wnull-dereference")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wduplicated-cond")
madnex_enable_cxx_compiler_flag(COMPILER_WARNINGS "Wmisleading-indentation")
